### PR TITLE
Update install script

### PR DESCRIPTION
**Pull request by bhelx**
Updates the install script. And the windows CI should pass now?

### CODE REVIEW

**Comment by mtb0x1** [comment]
> Updates the install script. And the windows CI should pass now?

the TAG is hardcoded in both scripts (Linux and windows), you need to change the windows one. (and maybe xD)

**Comment by bhelx** [comment]
Hmm still busted:

```
ARCH is x86_64.
Downloading extism-js version v1.0.0-rc11.
Installing extism-js.
Missing Binaryen tool(s).
Downloading Binaryen version version_116.
Installing Binaryen.
Install done !
extism-js: D:\a\_temp\52503bba-1216-4810-b0e0-f181ee5aa619.ps1:3
Line |
   3 |  extism-js --version
     |  ~~~~~~~~~
     | The term 'extism-js' is not recognized as a name of a cmdlet, function, script file, or executable program.
     | Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Error: Process completed with exit code 1.
```

**Comment by mtb0x1** [comment]
> Hmm still busted:
> 
> ```
> ARCH is x86_64.
> Downloading extism-js version v1.0.0-rc11.
> Installing extism-js.
> Missing Binaryen tool(s).
> Downloading Binaryen version version_116.
> Installing Binaryen.
> Install done !
> extism-js: D:\a\_temp\52503bba-1216-4810-b0e0-f181ee5aa619.ps1:3
> Line |
>    3 |  extism-js --version
>      |  ~~~~~~~~~
>      | The term 'extism-js' is not recognized as a name of a cmdlet, function, script file, or executable program.
>      | Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> Error: Process completed with exit code 1.
> ```

This for sure a PATH issue, even if the install script adds the PATH https://github.com/extism/js-pdk/blob/75f5224c74b290a01ea220f9cfc514ecb6695b10/install-windows.ps1#L32-L34. it's not refreshed and you need to start a fresh console.

The solution would be to add an extra step to the CI like so  : 
```diff
diff --git a/.github/workflows/ci_install.yml b/.github/workflows/ci_install.yml
index 111982b..9474c10 100644
--- a/.github/workflows/ci_install.yml
+++ b/.github/workflows/ci_install.yml
@@ -21,8 +21,12 @@ jobs:
         extism-js --version
       if: runner.os != 'Windows'

-    - name: Test Install Script (Windows)
+    - name: Test Install Script Part1 (Windows)
       run: |
         powershell -executionpolicy bypass -File .\install-windows.ps1
+      if: runner.os == 'Windows'
+
+    - name: Test Install Script Part2 (Windows)
+      run: |
         extism-js --version
       if: runner.os == 'Windows'
```

Still need to update the instruction in Readme to alert about this.

**Comment by bhelx** [comment]
Seems to still be failing. Going to let it go so we can release. @mtb0x1 when you get a moment could you open a PR? no rush i think it's fine to ignore the error for the time being.

**Pull request merged**
